-- Run once in the Supabase SQL Editor.
create table if not exists public.user_facts (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    fact text not null,
    source text not null default 'conversation',
    created_at timestamptz not null default now(),
    unique (user_id, fact)
);

create index if not exists user_facts_user_id_created_at_idx
    on public.user_facts (user_id, created_at desc);

create table if not exists public.bot_state (
    state_key text primary key,
    state_value jsonb not null,
    updated_at timestamptz not null default now()
);

create table if not exists public.user_sessions (
    user_id bigint primary key,
    session_data jsonb not null
);

-- Existing projects may have an older user_sessions table without
-- session_data. Add it without removing the legacy columns.
alter table public.user_sessions
    add column if not exists session_data jsonb;

create table if not exists public.message_sources (
    id bigint generated by default as identity primary key,
    user_id text not null,
    source text not null,
    created_at timestamptz not null default now()
);

create index if not exists message_sources_created_at_idx
    on public.message_sources (created_at desc);

create table if not exists public.user_favorites (
    user_id text not null,
    content text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

create index if not exists user_favorites_user_id_created_at_idx
    on public.user_favorites (user_id, created_at desc);

alter table public.user_facts enable row level security;
alter table public.bot_state enable row level security;
alter table public.user_sessions enable row level security;
alter table public.message_sources enable row level security;
alter table public.user_favorites enable row level security;

-- Keep RLS enabled and do not add public policies. The bot must use the
-- server-side service_role SUPABASE_KEY, which bypasses RLS. Never expose it
-- in a client or frontend application.