-- Run once in the Supabase SQL Editor.
create table if not exists public.user_facts (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    fact text not null,
    source text not null default 'conversation',
    created_at timestamptz not null default now(),
    unique (user_id, fact)
);

create index if not exists user_facts_user_id_created_at_idx
    on public.user_facts (user_id, created_at desc);

alter table public.user_facts enable row level security;

-- Keep RLS enabled and do not add public policies. The bot must use the
-- server-side service_role SUPABASE_KEY, which bypasses RLS. Never expose it
-- in a client or frontend application.